In [2]:
import numpy as np

m = np.array([[2,4,6],[1,2,3]], dtype = 'int')
m



array([[2, 4, 6],
       [1, 2, 3]])

In [3]:


t = m.T #transpone
t



array([[2, 1],
       [4, 2],
       [6, 3]])

In [4]:


a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print( "a =", a )
print( "b =", b )



a = [[6. 4.]
 [8. 9.]]
b = [[1. 7.]
 [1. 9.]]


In [5]:
c = np.vstack((a,b))
c


array([[6., 4.],
       [8., 9.],
       [1., 7.],
       [1., 9.]])

In [6]:


d = np.hstack((a,b))
d



array([[6., 4., 1., 7.],
       [8., 9., 1., 9.]])