In [ ]:
#CUESTIONATIOR UNIDAD 4

In [8]:
import numpy as np

a = np.array([[2, 4, 5, 6],
[0, 3, 7, 4],
[8, 8, 5, 2],
[1, 5, 6, 1]])

In [13]:
b = a[-3, -3]
b
print( a[1:, 1:3])

[[3 7]
 [8 5]
 [5 6]]


In [14]:
b = np.arange(1, 11)

In [16]:
print(b % 2 == 0)

[False  True False  True False  True False  True False  True]


In [17]:
print(b[b % 2 == 0])

[ 2  4  6  8 10]


In [19]:
a = np.array([[6, 5],
           [4, 7],
           [5, 2],
           [1, 2],
           [1, 3],
           [9, 7]])

In [21]:
print(a.mean(axis = 1))

[5.5 5.5 3.5 1.5 2.  8. ]


In [22]:
b = np.array([[6, 5, 4, 7, 5, 2],
              [1, 2, 1, 3, 9, 7]])
c = b[0,:]
b[b > 4] = 0
c

array([0, 0, 4, 0, 0, 2])

In [23]:
a = np.array([[6, 5, 4, 7, 5, 2], 
              [1, 2, 1, 3, 9, 7]])

In [27]:
print(type(a[a < a.mean()]))

[4 2 1 2 1 3]


In [26]:
print(type(a.std()))

<class 'numpy.float64'>
